---
- name: Network Backup - MikroTik
  hosts: mikrotik
  gather_facts: false

  vars_prompt:
    - name: mikrotik_password
      prompt: "MikroTik password"
      private: yes

  vars:
    ansible_password: "{{ mikrotik_password }}"

  roles:
    - network_backup


- name: Network Backup - Cisco
  hosts: cisco
  gather_facts: false

  vars_prompt:
    - name: cisco_password
      prompt: "Cisco password"
      private: yes

  vars:
    ansible_password: "{{ cisco_password }}"

  roles:
    - cisco_backup