---
- name: Collect MikroTik Device Information
  hosts: mikrotik
  gather_facts: false

  tasks:
    - name: Collect device information
      community.routeros.command:
        commands:
          - /system identity print
          - /system resource print
          - /system routerboard print
      register: device_info

    - name: Display device information
      debug:
        var: device_info.stdout
