---
- name: Backup Cisco
  cisco.ios.ios_command:
    commands:
      - show running-config
  register: cisco_backup

- name: Save Cisco backup
  ansible.builtin.copy:
    content: "{{ cisco_backup.stdout[0] }}"
    dest: "backups/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}.cfg"