---
- name: Backup MikroTik
  community.routeros.command:
    commands:
      - /export
  register: mikrotik_backup

- name: Save MikroTik backup
  ansible.builtin.copy:
    content: "{{ mikrotik_backup.stdout[0] }}"
    dest: "backups/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}.rsc"